# Generated by Django 4.2.1 on 2023-05-22 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividad',
            old_name='categoria_id',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='usuario_id',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='usuario_actividad',
            old_name='usuario_id',
            new_name='usuario',
        ),
    ]
