# Generated by Django 4.2.1 on 2023-05-27 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_rename_categoria_id_actividad_categoria_and_more'),
    ]

    operations = [
    ]
