# Generated by Django 4.2.1 on 2023-05-22 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='rol_id',
            new_name='rol',
        ),
    ]
