# Generated by Django 4.2.1 on 2023-05-27 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_rol'),
    ]

    operations = [
    ]
