# Generated by Django 4.2.1 on 2023-05-22 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=250)),
                ('fecha_inicio', models.DateTimeField(null=True)),
                ('fecha_entrega', models.DateTimeField(null=True)),
                ('fecha_cierre', models.DateTimeField(null=True)),
                ('observacion', models.CharField(max_length=250, null=True)),
                ('actividad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.actividad')),
                ('estado_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.estado')),
                ('usuario_id_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_solicitante', to=settings.AUTH_USER_MODEL)),
                ('usuario_id_tecnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_tecnico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rol_Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.estado')),
                ('rol_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.rol')),
            ],
        ),
    ]
