# Generated by Django 4.2.1 on 2023-05-27 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_rename_estado_id_rol_estado_estado_and_more'),
    ]

    operations = [
    ]
